declare function _exports(settings: any): {
    searchLowFares: Promise<any>;
    searchLowFaresAsync: Promise<any>;
    searchLowFaresRetrieve: Promise<any>;
    availability: Promise<any>;
    airPrice: Promise<any>;
    lookupFareRules: Promise<any>;
    airPricePricingSolutionXML: Promise<any>;
    createReservation: Promise<any>;
    ticket: Promise<any>;
    getUniversalRecordByPNR: Promise<any>;
    importUniversalRecordByPNR: Promise<any>;
    getUniversalRecord: Promise<any>;
    gdsQueue: Promise<any>;
    foid: Promise<any>;
    addSegments: Promise<any>;
    cancelUR: Promise<any>;
    flightInfo: Promise<any>;
    getTicket: Promise<any>;
    getTickets: Promise<any>;
    cancelTicket: Promise<any>;
    cancelBooking: Promise<any>;
    exchangeQuote: Promise<any>;
    exchangeBooking: Promise<any>;
    getEMDList: Promise<any>;
    getEMDItem: Promise<any>;
};
export = _exports;
