export const AIR_LOW_FARE_SEARCH_REQUEST: (params: any) => any;
export const AIR_RETRIEVE_LOW_FARE_SEARCH_REQUEST: (params: any) => any;
export const AIR_PRICE_FARE_RULES_REQUEST: (params: any) => any;
export const AIR_PRICE_REQUEST: (params: any) => any;
export const AIR_PRICE: (params: any) => any;
export const AIR_CREATE_RESERVATION_REQUEST: (params: any) => any;
export const AIR_TICKET: (params: any) => any;
export const AIR_REQUEST_BY_PNR: (params: any) => any;
export const GDS_QUEUE_PLACE: (params: any) => any;
export const UNIVERSAL_RECORD_RETRIEVE: (params: any) => any;
export function AIR_CANCEL_UR(params: any): any;
export function UNIVERSAL_RECORD_FOID(params: any): any;
export const UNIVERSAL_RECORD_MODIFY: (params: any) => any;
export const AIR_FLIGHT_INFORMATION: (params: any) => any;
export const AIR_GET_TICKET: (params: any) => any;
export const AIR_GET_TICKETS: (params: any) => any;
export const AIR_CANCEL_TICKET: (params: any) => any;
export const AIR_CANCEL_PNR: (params: any) => any;
export const AIR_EXCHANGE_QUOTE: (params: any) => any;
export const AIR_EXCHANGE: (params: any) => any;
export const AIR_EMD_LIST: (params: any) => any;
export const AIR_EMD_ITEM: (params: any) => any;
